import productImage from '../../assets/product.png';

export const mockProducts = [
  {
    id: '1',
    name: 'Rustic Wildflower Bouquet',
    price: 1599,
    image: productImage,
    description: 'A hand-tied bouquet of natural wildflowers, perfect for rustic weddings.',
    tags: ['rustic', 'wedding', 'wildflowers', 'seasonal', 'artisan', 'eco'],
    salesCount: 120,
  },
  {
    id: '2',
    name: 'Artisanal Rose Mix',
    price: 1899,
    image: productImage,
    description: 'Classic and elegant rose arrangement in a natural, artisanal style.',
    tags: ['roses', 'elegant', 'romantic', 'premium', 'artisan', 'best-seller'],
    salesCount: 310,
  },
  {
    id: '3',
    name: 'Lavender Charm',
    price: 1299,
    image: productImage,
    description: 'A fragrant mix of lavender and eucalyptus for calming occasions.',
    tags: ['lavender', 'aromatic', 'calming', 'gift', 'eco'],
    salesCount: 55,
  },
  {
    id: '4',
    name: 'Tropical Paradise',
    price: 2199,
    image: productImage,
    description: 'Vibrant arrangement featuring exotic tropical flowers and bird of paradise.',
    tags: ['tropical', 'exotic', 'colorful', 'luxury', 'new', 'artisan'],
    salesCount: 85,
  },
  {
    id: '5',
    name: 'Spring Tulip Collection',
    price: 1499,
    image: productImage,
    description: 'Fresh seasonal tulips in a rainbow of spring colors.',
    tags: ['tulips', 'spring', 'seasonal', 'colorful', 'on-sale', 'eco'],
    salesCount: 135,
  },
  {
    id: '6',
    name: 'White Wedding Classic',
    price: 2499,
    image: productImage,
    description: 'Pure white roses and lilies perfect for wedding ceremonies.',
    tags: ['wedding', 'white', 'formal', 'elegant', 'artisan'],
    salesCount: 97,
  },
  {
    id: '7',
    name: 'Sunflower Sunshine',
    price: 1399,
    image: productImage,
    description: 'Cheerful arrangement of sunflowers with rustic accents.',
    tags: ['sunflowers', 'bright', 'cheerful', 'summer', 'artisan', 'eco'],
    salesCount: 160,
  },
  {
    id: '8',
    name: 'Oriental Lily Dream',
    price: 1799,
    image: productImage,
    description: 'Fragrant oriental lilies with mixed seasonal greens.',
    tags: ['lilies', 'fragrant', 'oriental', 'premium', 'new', 'artisan'],
    salesCount: 90,
  },
  {
    id: '9',
    name: 'Birthday Celebration Mix',
    price: 1699,
    image: productImage,
    description: 'Colorful mixed flowers perfect for birthday celebrations.',
    tags: ['birthday', 'celebration', 'mixed', 'bright', 'on-sale', 'eco'],
    salesCount: 120,
  },
  {
    id: '10',
    name: 'Peaceful Sympathy',
    price: 1899,
    image: productImage,
    description: 'Elegant white and green arrangement expressing sympathy and peace.',
    tags: ['sympathy', 'peaceful', 'white', 'elegant'],
    salesCount: 45,
  },
  {
    id: '11',
    name: 'Rustic Rose Bouquet',
    price: 42,
    image: productImage,
    description: 'A charming bouquet of rustic roses with natural accents.',
    tags: ['best-seller', 'new', 'artisan', 'eco'],
    salesCount: 260,
  },
  {
    id: '12',
    name: 'Winter Harmony Arrangement',
    image: productImage,
    price: 49,
    description: 'A serene arrangement of winter blooms and greenery.',
    tags: ['seasonal', 'eco'],
    salesCount: 95,
  },
];
